- go.mod
The old module name `github.robot.car/cruise/daytona` is obsolete.
> Update module name to github.com/cruise-automation/daytona

- README.md
This functionality that was described in this line, wasn't ever actually added. Remove it from the docs for now.
> Remove line in documentation that wasn't actually implemented

- cmd/main.go
- go.mod
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/auth/aws.go
- pkg/auth/gcp.go
- pkg/auth/k8s.go
- pkg/auth/token_test.go
- pkg/helpers/testhelpers/testing.go
- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
* add missing error checks
* deindent package comments
* remove unnecessary type casts
There are still several more lint issues to fix. This is just a start.
This is branched off #4.
> Fix issues caught by golangci-lint

- .golangci.yml
- cmd/main.go
- go.mod
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/auth/aws.go
- pkg/auth/gcp.go
- pkg/auth/k8s.go
- pkg/auth/token_test.go
- pkg/helpers/testhelpers/testing.go
- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
* add `.golangci.yml` file
* now you can run linter with `golangci-lint run`
* disable `gosec` linter for one section of `auth_test.go`
**IMPORTANT: This doesn't fix all the linter issues. We'll have to fix those in followup PRs before we can enable CI.**
This is branched off #5.
> Add golangci-lint config

- Dockerfile
- Makefile
- pkg/auth/auth.go
Two changes, I can split them if you'd like.
1. I see the container as a sidecar restarting, and while I think it's because of Vault timeout, I'd like to see the error.
2. Tags the docker images using the latest docker tag. Appends the latest commit sha if not on a tag. So this branch is:
```
$ make image                                
docker build -t daytona:1.0.1-11-gfbb7f80  .
```
Future releases you can run `git tag -s v1.0.2` to tag and then the image tag will be up-to-date.
> Log renew errors & tag images with git tag

- README.md
Add additional spacing to make it visually clearer that the lists are
underneath the key above.
The original example would not work out of the box.
> Move serviceAccountName above initContainers key

- pkg/secrets/secrets.go
Introduce a Value Key prefix that can be used for retrieving a single value from a singular secret definition
Instead of attempting to retrieve every value within the vault path, only the value provided by `VAULT_VALUE_KEY_<secretID-SUFFIX>` will be returned to the ouput.
```
VAULT_SECRET_SINGLE=gcp/key/my-key-roleset
DAYTONA_SECRET_DESTINATION_UPPER=./output
VAULT_VALUE_KEY_UPPER=private_key_data
```
> Single value retrieval

- Makefile
Using the `-a` flag on build rebuilds the entire standard library for
daytona, which slows down the build immensely. There are plenty of
others ways to force a build to go through if there are problems, so 
we can remove this.
> Makefile: no need to re-build entire go stdlib

- Dockerfile
Today since git is not installed while building the docker image the version is not set, see below:
```
---> Running in e12300c7f495
CGO_ENABLED=0 go build -ldflags '-s -w -X main.version=' -o daytona cmd/daytona/main.go
make: git: No such file or directory
```
Adding git will allow to retrieve the version, and generate the image like:
```
---> Running in f6d8e64950e9
CGO_ENABLED=0 go build -ldflags '-s -w -X main.version=v1.1.2-1-g50f1ad1' -o daytona cmd/daytona/main.go
```
> Fix docker build / make image: adding git to Dockerfile builder

- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
If vault api return an map we are currently panicking, see below:
```
panic: interface conversion: interface {} is map[string]interface {}, not string
goroutine 1 [running]:
github.com/cruise-automation/daytona/pkg/secrets.(*SecretDefinition).addSecrets(0xc0001c7730, 0xc00029a770, 0xc0000bc090, 0x0, 0x4)
/Users/myuser/daytona/pkg/secrets/secrets.go:235 +0x9c8
github.com/cruise-automation/daytona/pkg/secrets.SecretFetcher(0xc00029a770, 0x0, 0x0, 0x7ffeefbff6dd, 0x21, 0x177f0fc, 0x33, 0x0, 0x1763bb4, 0xa, ...)
/Users/myuser/daytona/pkg/secrets/secrets.go:128 +0x62a
main.main()
/Users/myuser/daytona/cmd/daytona/main.go:202 +0x318
```
This fix will avoid and panic and replicate `vault read` behavior.
```
$ vault read -field=foo secret/foo
map[bar:baz]
```
> Fix panic when vault return a map

- Makefile
- pkg/secrets/reader.go
- pkg/secrets/reader_test.go
- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
The previous implementation had the potential to encounter a worker deadlock due to the use of buffered channels with a length of 100. If there weren't enough workers to process the incoming data, that channel would reach capacity. 
---
- Implement `ReadPaths` in lieu of individual `AsyncRequestKeyPath` and `ReadSecretResult` functions
- Use a buffered channel for the secret reader so that secret definitions with >= 100 paths don't deadlock the worker
- Improve logging and error reporting
- Update the worker manager to react to os signals, ensuring the worker
pool is shut down cleanly
- Added a RWMutex to SecretDefinition so that the secrets map can be
locked for reading and writing
> Parallel reader improvements

- CHANGELOG.md
- pkg/helpers/file.go
- pkg/helpers/file_test.go
- pkg/pki/pki.go
- pkg/secrets/secrets.go
Previously if a secret destination path was provided that didn't fully exist, DAYTONA would fail to write the secret. Parent directories are now created as needed in order to successfully write the secret to file.
Previous Success: `/tmp/ssshhhh.json`
Previous Failure: `/tmp/this/that/another/secret.json`
Current Success: `/tmp/ssshhhh.json`
Current Success: `/tmp/this/that/another/secret.json`
> Ability to write secrets to paths whose parents do not exist

- README.md
Document `VAULT_VALUE_KEY_` capabilities, finally.
> Improve Secret Definition documentation

- README.md
- cmd/daytona/main.go
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/auth/k8s.go
- pkg/config/config.go
- pkg/config/config_test.go
Right now each auth method has its own flag: `--k8s-auth`, `--aws-auth`, etc.
This doesn't scale and we should migrate to an input method: `--auth-method` that takes an input for which type of auth to do (k8s/aws/gcp/azure, etc.)
Also  move `{gcp,k8s,aws}-auth-mount` to `auth-mount` and move the existing `auth-mount` to `auth-path`,  Where `auth-mount`is used to generate a `auth-path` if not provided.  The defaults for `auth-mount` and `auth-path` are handled during the validation of the `auth-method`
**This is a breaking change of the API.**
> Simplify auth method

- CHANGELOG.md
- README.md
- cmd/daytona/main.go
- pkg/auth/auth.go
- pkg/auth/azure.go
- pkg/config/config.go
fixes issue #65 
Creates a Auth request to an[ Azure Auth backend](https://www.vaultproject.io/docs/auth/azure).  It pulls instance metadata from the [Azure metadata endpoint](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=linux#instance-metadata) and a JWT from the [Managed Identities endpoint](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-go)
To use the Azure Auth  set `--azure-auth=true` flag or the environment variable `AZURE_AUTH=true`. An optional `--azure-auth-mount` or `AZURE_AUTH_MOUNT` can be used to configure what Azure Auth backend is used, the default is `azure`.
> Add Azure Auth method

- CHANGELOG.md
- cmd/daytona/main.go
This PR updates Daytona to use a custom HTTP User-Agent, instead of the default Go `http` module UA (`Go-http-client/2.0"`).
> Set DAYTONA/<version> as the User-Agent instead of the default Go http UA.

- CHANGELOG.md
- pkg/auth/azure.go
This fixes https://github.com/cruise-automation/daytona/issues/81 by upgrading the Azure Metadata API version to the latest and adding the ability to decode and utilize the `vmScaleSetName` with the supported auth mechanism on the azure auth plugin [here](https://github.com/hashicorp/vault-plugin-auth-azure/blob/9ead1b884731703eabc6efd82a358c7b31038ec1/path_login.go#L41).
> Add VMScaleSet to Azure Auth method

- CHANGELOG.md
- pkg/auth/auth.go
- pkg/auth/token_test.go
- pkg/pki/pki.go
- pkg/secrets/secrets.go
- Changed the signature of `checkToken` and `checkFileToken` to return `error` instead of `bool`, so that more detailed information can be relayed about the failure.
- Improved logging message clarity and intention
- Expose output errors that were previously not captured
> Improve logging output to be more informative

- CHANGELOG.md
- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
Previously, when reading a singular secret definition and a singular output destination was specified, if more than one data key was returned, a data key value would be chosen at random, causing inconsistencies in the secret data being written. The new behavior defaults to always reading the default of `value` unless explicitly overwritten by `VAULT_VALUE_KEY_`.
The value `standard` is written to `/vault/secret-value`:
```
VAULT_SECRET_TEST=secret/path/testing
DAYTONA_SECRET_DESTINATION_TEST=/vault/secret-value
"data": {
"value": "standard",
"password": "nonstandard"
}
```
The value `nonstandard` is written to `/vault/secret-value`:
```
VAULT_SECRET_TEST=secret/path/testing
DAYTONA_SECRET_DESTINATION_TEST=/vault/secret-value
VAULT_VALUE_KEY_TEST=password
"data": {
"value": "standard", …
```
> Prevent inconsistencies when reading singular secrets paths that contain multiple keys 

- .gitignore
- pkg/daytona/options.go
- pkg/daytona/options_test.go
- pkg/daytona/unmarshal.go
- pkg/daytona/unmarshal_test.go
Introducing a way to populate go structs with secret data from Vault.
`SecretUnmarshler` reads data from Vault and stores the result(s) in the a provided struct. This can be useful to inject sensitive configuration items directly into config structs.
The following field types are currently supported:
- struct
- string
- bool
- time.Duration
- signed ints
- float32, float64
**Secret Data Example 1**: Consider the design of the following secret path: `secret/application`, that contains
several sub-keys:
- API_KEY - the data being stored in the data key 'value'
- DB_PASSWORD - the data being stored in the data key 'value'
Reading the path `secret/application/api_key` returns the data:
```
{
"data": {
"value": "anapikey"
}
}
```
Reading the path  `secret/application/db_password` returns the …
> Introducing secret Unmarshal function

- pkg/auth/auth.go
- pkg/auth/auth_test.go
Fixes token renewal panic as reported in #95 
Break out token renewal capabilities into its own function, with improved validation to avoid a nil pointer dereference.
Includes tests for validation.
> Fix token renewal panic

- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
This fixes a bug where `SECRET_ENV=true` only worked if `DAYTONA_SECRET_DESTINATION_THING` is also set, even though that is not expected.
Fix #99
> Write env variable for single key, if not also written to file

- cmd/daytona/main.go
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/config/config.go
- pkg/config/config_test.go
Daytona currently does not perform authentication if a valid vault token exists as the environment variable `VAULT_TOKEN` or as a file in the specified `TokenPath` argument. To better support this behavior, I'm adding a "no auth" option in which authentication will be disabled. If a token cannot be found in the environment variable or file, Daytona will simply error out. 
This should make it easier to support cases where an existing token is used and no custom auth is desired. In our specific case, this enables us to avoid any risk of duplicate calls to Vault which can pose a scalability risk. 
Specific changes:
- support a `--no-auth` argument or `NO_AUTH` environment variable to indicate that no authentication scheme is desired
- (bug fix) report the Azure auth scheme as a valid option …
> Add support for no authentication scheme
